name:ScoreboardPE
main: ScoreboardPE\MainClass
version: 2.0.0
api: [2.0.0]

load: Scoreboard
author: NGGNewGen
description: loads a scoreboard at the bottom of then screen 
website: https://github.com/PocketMine/ScoreboardPE
commands: /sb load 
 example:
  description: Example command
  usage: "Usage: /example"
  permission: scoreboardpe.command.use
permissions:
 Scoreboardpe.command.example:
  description: "Allows the user to run the scoreboard command"
  default: true
